export type Game = {
	title: string;
	tagline: string;
	description?: string;
	url: string;
	date: string;
	showcase?: boolean;
};
export const games: Game[] = [
	{
		title: 'SubLight Flotsam',
		tagline: "scavenge the fathoms",
		description: "sublight flotsam . a lost and found ocean arcology . . a submariner in miniature a false fish of lantern . . . find six signs of sub-aphotic activity scavenge the fathoms and succeed",
		url: 'https://sweetheartsquad.itch.io/sublight-flotsam',
		date: '2025 January 27',
		showcase: false,
	},
	{
		title: 'How am I Still Waiting for the Bus?',
		tagline: "You've been waiting for your bus...",
		description: "And waiting. And waiting. And now you're dead! Your soul is being drawn toward the afterlife, but you have to fight the urge. You can't die -- you have to get to WORK!!",
		url: 'https://sweetheartsquad.itch.io/how-am-i-still-waiting-for-the-bus',
		date: '2024 December 21',
		showcase: true,
	},
	{
		title: 'BLOOD in the SKY: DEAD OR ALIVE',
		tagline: 'A story-driven mech battler inspired by Battleship',
		description: "Build your mech using a variety of weapons, shields, and parts. Locate and destroy your opponent's cockpit before they get yours.",
		url: 'https://sweetheartsquad.itch.io/blood-in-the-sky',
		date: '2024 July 18',
		showcase: true,
	},
	{
		title: 'Teddy Typtoes Tickle Tower',
		tagline: "Tickle Teddy's Toes in this Delightful Typing Test",
		description: 'Practice your typing as you tickle Teddy\'s toes. Put your best foot forward as you recreate famous literary passages, now with 50% more "footnotes"!',
		url: 'https://sweetheartsquad.itch.io/teddy-typtoes-tickle-tower',
		date: '2024 January 28',
	},
	{
		title: 'Taxi Quest 66',
		tagline: '"Perfect weather, isn\'t it?"',
		description: 'A game about scaling a mountain.',
		url: 'https://sweetheartsquad.itch.io/taxi-quest-66',
		date: '2023 December 01',
	},
	{
		title: 'TOC TOC',
		tagline: 'Explore the abandoned house next door where no one lives...',
		description:
			"<p>It's a lazy Sunday afternoon, and you decide to explore the abandoned house next door. Soon, you find yourself on a tiny quest that takes you through every corner of this strange house. Puzzle your way through three levels with three unique art styles.</p><p>Inspired by the Famicase <a href='https://famicase.com/23/softs/122.html'>TOC TOC</a> by <a href='https://withkoji.com/@AQUILES'>AQUILES</a>.</p>",
		url: 'https://sweetheartsquad.itch.io/toc-toc',
		date: '2023 August 13',
	},
	{
		title: 'Turnip the Heat!',
		tagline: 'SALTY, SUCCULENT & SEXY',
		description:
			"<p>The root of a good party is a good host: keep the tub toasty and clean, get the drinks and d'ourves flowing, and satisfy your steamy guests in this rootin tootin party panic! Just keep an eye on your InstaYam or your bustling buds buzz'll be busted...</p><p>Made for Global Game Jam 2023 with PixiJS. All assets created in JS Paint.</p>",
		url: 'https://sweetheartsquad.itch.io/turnip-the-heat',
		date: '2023 February 5',
	},
	{
		title: 'Bleak',
		tagline: 'A post-apocalyptic farming sim with a vampiric twist',
		description: 'A cute and laidback nightly farm simulator, where you grow strange and glorious flowers for a charming cast of characters.',
		url: 'https://sweetheartsquad.itch.io/bleak',
		date: '2022 November 30',
		showcase: true,
	},
	{
		title: 'Taxi Quest 65',
		tagline: '"Is that REALLY necessary?"',
		description: 'A sequel six years in the making to Taxi Quest 64.',
		url: 'https://sweetheartsquad.itch.io/taxi-quest-65',
		date: '2022 January 29',
	},
	{
		title: 'We Follow The Fickle Path',
		tagline: 'A story about ants.',
		description: 'A sister is One, and one may be lost.<br /><br />A sister of Many, will always have sisters.',
		url: 'https://sweetheartsquad.itch.io/we-follow-the-fickle-path',
		date: '2021 November 28',
		showcase: true,
	},
	{
		title: 'Advanced Bipedal Battle Armour: The Name of the Game',
		tagline: 'Dueling in 2.5D',
		description: 'It all comes down to this. Friends, lovers, now rivals: Duel it out with your prized Advanced Bipedal Battle Armour to prevent a cataclysmic merger of worlds!',
		url: 'https://sweetheartsquad.itch.io/advanced-bipedal-battle-armour',
		date: '2021 October 05',
	},
	{
		title: 'Short Rest',
		tagline: 'A party-based roguelike deckbuilder',
		description: "Every card is precious, but some things are more precious than cards... Carefully strategize as you make your way through the dragon's dungeon, and save the village from calamity!",
		url: 'https://sweetheartsquad.itch.io/short-rest',
		date: '2021 September 12',
		showcase: true,
	},
	{
		title: 'Rupert Rabbit in: Murder, My Bunny',
		tagline: 'Magic, murder, and mystery in a small town bar.',
		description: 'Marcel the Magnifical is scheduled to go on tonight, but something is amiss: explore a night of magic, murder, and mystery in a small town bar.',
		url: 'https://sweetheartsquad.itch.io/murder-my-bunny',
		date: '2021 April 25',
	},
	{
		title: "Finder's Keplers",
		tagline: 'Draw and guess constellations with friends',
		description:
			'This is an asynchronous multiplayer game for 2 or more players. Draw constellations using the generated prompts/starmap, and then send them to your friends and see if they can guess them all!',
		url: 'https://sweetheartsquad.itch.io/finders-keplers',
		date: '2021 January 31',
	},
	{
		title: 'VARIETY MEGAJAM 2020 Retrospective',
		tagline: 'A look back at 10 games made over 10 days.',
		url: 'https://sweetheartsquad.itch.io/variety-megajam-2020-retrospective',
		date: '2021 January 01',
	},
	{
		title: 'truck(r)ing REMASTERED',
		tagline: 'the truck game you know and love, but better',
		url: 'https://sweetheartsquad.itch.io/truckring-remastered',
		date: '2020 December 31',
	},
	{
		title: "The Dungeoneer's Cookbook",
		tagline: 'Roasts, Bakes, and More for The Practical Adventurer',
		url: 'https://sweetheartsquad.itch.io/the-dungeoneers-cookbook',
		date: '2020 December 30',
	},
	{
		title: 'SUPERmarket SPY 2D',
		tagline: 'A STRATEGIC SURVEILLANCE SORTIE',
		url: 'https://sweetheartsquad.itch.io/supermarket-spy-2d',
		date: '2020 December 29',
	},
	{
		title: "Le Prix d'Escalier",
		tagline: '"The Price of Stairs"',
		description: 'Variant of five-card draw poker.',
		url: 'https://sweetheartsquad.itch.io/le-prix-descalier',
		date: '2020 December 28',
	},
	{
		title: 'Beaks of Rage',
		tagline: 'An RPG beat-em-up about a regular chicken.',
		url: 'https://sweetheartsquad.itch.io/beaks-of-rage',
		date: '2020 December 27',
	},
	{
		title: 'Donut Get Burned!!',
		tagline: 'Save a donut from confectionary conundrums.',
		url: 'https://sweetheartsquad.itch.io/donut-get-burned',
		date: '2020 December 26',
	},
	{
		title: 'Collar Me Impressed',
		tagline: 'Design an elegant cat collar with ease and speed!',
		description: 'A cute cat collar dress-up game with dozens of feline combinations and accessories to choose from!',
		url: 'https://sweetheartsquad.itch.io/collar-me-impressed',
		date: '2020 December 25',
		showcase: true,
	},
	{
		title: 'Collar Me Impressed',
		tagline: 'Design an elegant cat collar with ease and speed!',
		url: 'https://sweetheartsquad.itch.io/collar-me-impressed',
		date: '2020 December 25',
	},
	{
		title: 'JET LI IS THE ONE (2001) ASKING YOU TO GET HIM A COFFEE',
		tagline: 'And he likes it strong.',
		url: 'https://sweetheartsquad.itch.io/jet-li-is-the-one-2001-coffee',
		date: '2020 December 24',
	},
	{
		title: 'truck(r)ing',
		tagline: 'go in a loop and collect loops',
		url: 'https://sweetheartsquad.itch.io/truckring',
		date: '2020 December 23',
	},
	{
		title: 'I Can Fix It!',
		tagline: 'A party game about problems and solutions.',
		description: 'A printable party game about problems and solutions inspired by games like Snake Oil and Cards Against Humanity.',
		url: 'https://sweetheartsquad.itch.io/i-can-fix-it',
		date: '2020 February 02',
	},
	{
		title: 'ROUND TABLE',
		tagline: 'Shoulder your burdens.',
		description:
			'The Good Queen has passed, as all must. The burden to rule falls now to The Naïve Heir, and their table of knights. Inspired by the Famicase <a href="https://famicase.com/19/softs/024.html">Round Table</a> by <a href="https://twitter.com/kump">Matt Kump</a>.',
		url: 'https://sweetheartsquad.itch.io/round-table',
		date: '2019 August 21',
	},
	{
		title: "Fortune's Fervour",
		tagline: 'What does your future hold?',
		description: "Explore and learn your fate. A diviner made with artwork generated within 24h by <a href='https://twitter.com/SpritesByBitsy'>@SpritesByBitsy</a>.",
		url: 'https://sweetheartsquad.itch.io/fortunes-fervour',
		date: '2019 May 15',
	},
	{
		title: 'Homeward Bound',
		tagline: 'You wake up in an endless ocean...',
		description:
			"A group of seven people find themselves on a ship in the middle of an endless ocean, with no recollection of how they got there. Based on the <a href='https://www.imdb.com/title/tt0014138/'>1923 film</a> of the same name.",
		url: 'https://sweetheartsquad.itch.io/homeward-bound',
		date: '2019 January 28',
	},
	{
		title: 'Goodbye BURGER CITY',
		tagline: 'city of burgers',
		description: 'I never saw American Graffiti.',
		url: 'https://sweetheartsquad.itch.io/goodbye-burger-city',
		date: '2019 January 20',
	},
	{
		title: '<3 SWEETHEART SQUAD MANIFESTO <3',
		tagline: 'the only slightly fictionalized ramblings of a game dev chat log',
		url: 'https://sweetheartsquad.itch.io/sweetheart-squad-manifesto',
		date: '2018 February 12',
	},
	{
		title: 'Tuned in... to Love',
		tagline: 'Ham it up on the airwaves and chew the rag with a variety of eligible amateur enthusiasts in this automotive dating sim.',
		url: 'https://sweetheartsquad.itch.io/tuned-in-to-love',
		date: '2018 January 28',
	},
	{
		title: 'The Baseball Kid: New Beginnings',
		tagline: 'A Select-Your-Own-Plot adventure.',
		description: 'A throwback to the CYOA novels of our youth. Become the Baseball Kid as you explore Fenway Park.',
		url: 'https://sweetheartsquad.itch.io/the-baseball-kid',
		date: '2017 December 01',
	},
	{
		title: 'BONZEN',
		tagline: 'Shape a sense of zen.',
		description:
			'Nothing grows in space, at least not with some help. Join an old man in his quest to bring back beautiful greenery that once covered his lost planet. Take a step back from space drama and a step into his biodome to cultivate tiny bonsai trees and find some inner peace.',
		url: 'https://sweetheartsquad.itch.io/bonzen',
		date: '2017 November 07',
	},
	{
		title: 'Rōshigumi',
		tagline: 'A traitor threatens the Shogun in this tense shoot-em-up.',
		description: "You are a ronin, hired by the Rōshigumi to protect the Shogun on his visit to Kyoto. The only problem is, there's a traitor in your midst.",
		url: 'https://sweetheartsquad.itch.io/roshigumi',
		date: '2017 September 26',
		showcase: true,
	},
	{
		title: 'A Visitor on Venus',
		tagline: 'A low-rez FMV visual novel about a vacation gone wrong.',
		description:
			'On your way to Charon for a well-deserved vacation, your ship crash-lands on Venus -- a planet owned entirely by an eccentric quadrillionaire. Explore his lavish estate and find parts to repair your ship.',
		url: 'https://sweetheartsquad.itch.io/a-visitor-on-venus',
		date: '2017 June 14',
	},
	{
		title: 'AS Mall World',
		tagline: 'Ancient Secrets: Mall World',
		description: 'Journey through Mall World, purchase powerful artifacts, and maybe even solve the mystery of true love.',
		url: 'https://sweetheartsquad.itch.io/as-mall-world',
		date: '2017 April 25',
	},
	{
		title: 'BEAN',
		tagline: "It's a regular old swimming race -- but if you finish with the bean, you lose!",
		url: 'https://sweetheartsquad.itch.io/bean',
		date: '2017 January 22',
	},
	{
		title: 'Bouncing Balls with the Boing Boing Boys',
		tagline: 'Bouncy Battles for 2-4 Buddies',
		description: 'Chaotic local multiplayer deathmatch for 2-4 players.',
		url: 'https://sweetheartsquad.itch.io/bouncing-balls-with-the-boing-boing-boys',
		date: '2016 December 13',
	},
	{
		title: 'server.hack()',
		tagline: 'a single-page cyberpunk board game for 2-4 players',
		description: 'A single-page cyberpunk print-and-play board game for 2-4 players.',
		url: 'https://sweetheartsquad.itch.io/server-hack',
		date: '2016 November 13',
	},
	{
		title: 'DYSCOVR',
		tagline: 'the open source platform for intergalactic archaeology',
		description: 'An asynchronous online multiplayer sandbox about describing ancient alien technology.',
		url: 'https://sweetheartsquad.itch.io/DYSCOVR',
		date: '2016 August 30',
	},
	{
		title: "STRUNG OUT in heaven's high",
		tagline: 'hitting an all-time low',
		description:
			"Do you remember a cat that's been in such an early game? We know that the cat was sent to space. Connected, monitorized, trapped in a tin can. A cat sent to die for the sake of science. High on catnip his brain envisioned adventures of space discovery, <strike>intergalactic battles, heroes and glory</strike>. But this is the final chapter of the Star Cats saga and the addiction to catnip is now out of control. Strung-out on heaven's high - hitting an all-time low - <strike>the little green wheels are following him</strike>.",
		url: 'https://sweetheartsquad.itch.io/strung-out-in-heavens-high',
		date: '2016 July 28',
	},
	{
		title: '#MURDERJAM2016',
		tagline: "A game jam gone wrong, and it's up to your selective hearing to solve the mystery!",
		url: 'https://sweetheartsquad.itch.io/murderjam2016',
		date: '2016 June 26',
	},
	{
		title: 'Deluge Suites',
		tagline: 'Can you keep your hotel afloat?',
		description: 'A cheery little isometric game about managing a business during the end of the world.',
		url: 'https://sweetheartsquad.itch.io/deluge-suites',
		date: '2016 May 15',
	},
	{
		title: 'Purity',
		tagline: 'Protect your fragile heart from the infectious impurities!',
		description: 'A reverse bullet-hell game with a hyper-agressive aesthetic and a steep difficulty curve.',
		url: 'https://sweetheartsquad.itch.io/purity',
		date: '2016 April 18',
	},
	{
		title: 'Drive Forever',
		tagline: "You're going to have to keep this up forever.",
		url: 'https://sweetheartsquad.itch.io/drive-forever',
		date: '2016 April 17',
	},
	{
		title: '★ Creamie Buddies ★',
		tagline: 'Scoop Me Up!',
		url: 'https://sweetheartsquad.itch.io/creamie-buddies',
		date: '2016 April 13',
	},
	{
		title: 'Good Duel Game',
		tagline: 'A good duel game',
		url: 'https://sweetheartsquad.itch.io/good-duel-game',
		date: '2016 April 06',
	},
	{
		title: 'Stone Cold Sexy',
		tagline: 'pose 4 peeps',
		url: 'https://sweetheartsquad.itch.io/stone-cold-sexy',
		date: '2016 April 05',
	},
	{
		title: 'SODZEN',
		tagline: 'A little pot of paradise.',
		description: 'A 64 by 64 pixel zen experiment created for a game jam. See other entries I worked on <a target="_blank" href="/stuff/LOWREZJAM2016">here</a>.',
		url: 'https://sweetheartsquad.itch.io/sodzen',
		date: '2016 April 03',
	},
	{
		title: 'CODENAME: PAWN',
		tagline: 'You have to kill the sleeper agents.',
		description: 'A surveillance-themed RTS-lite. This is a game of patience and attention to detail.',
		url: 'https://sweetheartsquad.itch.io/codename-pawn',
		date: '2016 April 01',
	},
	{
		title: 'Party, Darling?',
		tagline: 'A weird & abrasive sci-fi adventure game',
		description: 'A house party turned multi-dimensional murder mystery. Search for clues in a potentially infinite number of procedurally generated mansions.',
		url: 'https://sweetheartsquad.itch.io/party-darling',
		date: '2016 March 09',
		showcase: true,
	},
	{
		title: 'Rip It! Grip It! Sip It!',
		tagline: 'The exorcising adventures of Father Skyler, punk priest extraordinaire.',
		description: 'Rip, grip, and sip some demons out of their unwilling human hosts!',
		url: 'https://sweetheartsquad.itch.io/rip-it-grip-it-sip-it',
		date: '2016 February 04',
	},
	{
		title: 'Super Spaceship 64',
		tagline: 'inspired by Starfox and Superman 64',
		url: 'https://sweetheartsquad.itch.io/super-spaceship-64',
		date: '2016 January 25',
	},
	{
		title: 'Llammigration (demo)',
		tagline: 'Learning With Llama',
		description: 'An unfinished educational game in the vein of Oregon Trail',
		url: 'https://sweetheartsquad.itch.io/llammigration',
		date: '2015 December 21',
	},
	{
		title: 'Go On',
		tagline: 'A two-button game about growing up.',
		description: 'Originally just a lighting experiment, this game was inspired by <em>Passage</em> and is awfully moody.',
		url: 'https://sweetheartsquad.itch.io/go-on',
		date: '2015 December 15',
	},
	{
		title: 'Taxi Quest 64',
		tagline: 'A short experiment for Ludum Dare 34.',
		description: 'A game about driving around a mercenary in your taxi.',
		url: 'https://sweetheartsquad.itch.io/taxi-quest-64',
		date: '2015 December 15',
	},
	{
		title: 'SweetBeats',
		tagline: 'A simple procedural beat generator.',
		url: 'https://sweetheartsquad.itch.io/sweetbeats',
		date: '2015 November 15',
	},
	{
		title: "Dad, Don't Open Spyware!!!",
		tagline: 'Lo-fi cyberspace meets horde-mode action for a lesson in parenting.',
		description:
			"This is a game of coordination. As a Mother/Son hacker team, you must press your special attack buttons at the same time to initiate powerful moves. Don't be a victim of bad data -- defeat waves of viruses and net nasties to save the day!",
		url: 'https://sweetheartsquad.itch.io/dad-dont-open-spyware',
		date: '2015 July 03',
	},
	{
		title: "Hare's Hollow",
		tagline: 'A visual novel about funny animals, and the nature of Nature.',
		description:
			"An exciting visual novel for 3 of your 5 senses. Play as Fox and explore Hare's Hollow to discover the secret story of the animals. Originally developed in a custom C++ OpenGL engine, and later ported to WebGL.",
		url: 'https://sweetheartsquad.itch.io/hares-hollow',
		date: '2015 July 01',
	},
];
