export const games = [
	{
		title: "How am I Still Waiting for the Bus?",
		tagline: "You've been waiting for your bus...",
		description: "And waiting. And waiting. And now you're dead! Your soul is being drawn toward the afterlife, but you have to fight the urge. You can't die -- you have to get to WORK!!",
		url: "https://sweetheartsquad.itch.io/how-am-i-still-waiting-for-the-bus",
		urlPoster: "assets/video/bus.png",
		urlVideo: "assets/video/bus.mp4",
	},
	{
		title: "BLOOD in the SKY: DEAD OR ALIVE",
		tagline: "A story-driven mech battler inspired by Battleship",
		description: "Build your mech using a variety of weapons, shields, and parts. Locate and destroy your opponent's cockpit before they get yours.",
		url: "https://sweetheartsquad.itch.io/blood-in-the-sky",
		urlPoster: "assets/video/blood.png",
		urlVideo: "assets/video/blood.mp4",
	},
	{
		title: "Bleak",
		tagline: "A post-apocalyptic farming sim with a vampiric twist",
		description: "A cute and laidback nightly farm simulator, where you grow strange and glorious flowers for a charming cast of characters.",
		url: "https://sweetheartsquad.itch.io/bleak",
		urlPoster: "assets/video/bleak.png",
		urlVideo: "assets/video/bleak.mp4",
	},
	{
		title: "We Follow The Fickle Path",
		tagline: "A story about ants.",
		description: "A sister is One, and one may be lost.<br /><br />A sister of Many, will always have sisters.",
		url: "https://sweetheartsquad.itch.io/we-follow-the-fickle-path",
		urlPoster: "assets/video/fickle path.png",
		urlVideo: "assets/video/fickle path.mp4",
	},
	{
		title: "Short Rest",
		tagline: "A party-based roguelike deckbuilder",
		description: "Every card is precious, but some things are more precious than cards... Carefully strategize as you make your way through the dragon's dungeon, and save the village from calamity!",
		url: "https://sweetheartsquad.itch.io/short-rest",
		urlPoster: "assets/video/short rest.png",
		urlVideo: "assets/video/short rest.mp4",
	},
	{
		title: "Collar Me Impressed",
		tagline: "Design an elegant cat collar with ease and speed!",
		description: "A cute cat collar dress-up game with dozens of feline combinations and accessories to choose from!",
		url: "https://sweetheartsquad.itch.io/collar-me-impressed",
		urlPoster: "assets/video/collar me impressed.png",
		urlVideo: "assets/video/collar me impressed.mp4",
	},
	{
		title: "Party, Darling?",
		tagline: "A weird & abrasive sci-fi adventure game",
		description: "A house party turned multi-dimensional murder mystery. Search for clues in a potentially infinite number of procedurally generated mansions.",
		url: "https://sweetheartsquad.itch.io/party-darling",
		urlPoster: "assets/video/party.png",
		urlVideo: "assets/video/party.mp4",
	},
	{
		title: "Rōshigumi",
		tagline: "A traitor threatens the Shogun in this tense shoot-em-up.",
		description: "You are a ronin, hired by the Rōshigumi to protect the Shogun on his visit to Kyoto. The only problem is, there's a traitor in your midst.",
		url: "https://sweetheartsquad.itch.io/roshigumi",
		urlPoster: "assets/video/roshigumi.png",
		urlVideo: "assets/video/roshigumi.mp4",
	},
];
